name: bookkeeping
description: A lightweight bookkeeping app built with Flutter and Drift.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  path_provider: ^2.1.2

  # UI
  intl: ^0.19.0
  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
